### ISSUE TITLE
Why do gradle types have to be fully qualified?

### ISSUE THREAD

**Issue by ndw** [ndw/xmlcalabash1-gradle#1]
In theory `task: XMLCalabashTask` should work, but in practice `com.xmlcalabash.XMLCalabashTask` is required.

**Comment by JanVanderschoot** [comment]
Probably trivial, but what worked for me is
`import com.xmlcalabash.XMLCalabashTask`
in build.gradle.

**Comment by ndw** [comment]
Yes. I was just confused.
